name: Publish image to GitHub Container Registry
on:
  push:
    branches:
      - master
      - develop
      - main
      - 'release*'
  workflow_dispatch:
    inputs:
      branch_name:
        description: Branch to build from
        default: develop
        required: true
jobs:
  push:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          fetch-depth: 2
          ref: '${{ github.event.inputs.branch_name }}'

      - uses: actions/checkout@v4
        if: github.event_name == 'push'

      - name: Get tags
        run: git fetch --tags origin

      - name: Set GitHub account and container registry repo variables
        run: |
          echo "GITHUB_ACCOUNT=${GITHUB_REPOSITORY%%/*}" >> $GITHUB_ENV
          echo "GH_CONTAINER_REGISTRY_REPO=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_ACCOUNT }}
          password: ${{ secrets.GH_PAT}}

      - name: Push image
        env:
          GITHUB_ACCOUNT: ${{ env.GITHUB_ACCOUNT }}
          GH_CONTAINER_REGISTRY_REPO: ${{ env.GH_CONTAINER_REGISTRY_REPO }}
        run: |
          # Check if the current commit has a tag and use it; otherwise, use the short SHA of the HEAD commit
          export COUNTRY_CONFIG_VERSION=$(git describe --tags --exact-match 2>/dev/null || git rev-parse --short=7 HEAD)
          echo "Publishing a Docker image with a tag $COUNTRY_CONFIG_VERSION"
          bash build-and-push.sh && unset COUNTRY_CONFIG_VERSION
